name = "Riemann"
defaultTargets = ["Riemann"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "Riemann"

[[lean_lib]]
name = "PrimeNumberTheoremAnd"

[[lean_lib]]
name = "StrongPNT"

[[lean_lib]]
name = "VD"

[[lean_lib]]
name = "PhysLean"
