name = "Riemann"
defaultTargets = ["Riemann"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = true
relaxedAutoImplicit = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "Riemann"

[[lean_lib]]
name = "PrimeNumberTheoremAnd"

[[lean_lib]]
name = "StrongPNT"

[[lean_lib]]
name = "VD"

[[lean_lib]]
name = "PhysLean"

[[lean_lib]]
name = "Carleson"

[[lean_lib]]
name = "DeRhamCohomology"

[[lean_lib]]
name = "CReals"

[[lean_lib]]
name = "Notes"

[[lean_lib]]
name = "GibbsMeasure"

[[lean_lib]]
name = "RiemannRecognitionGeometry"
